import Link from 'next/link';
import { ChevronRight, Clock, MapPin, User as UserIcon } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { cn } from '@/lib/utils/cn';
import { formatRelative } from '@/lib/utils/format';
import type { ActionItemSummary } from '@/lib/db/kpi';

/**
 * Action items section for the Overview page.
 *
 * Shows the daily checklist generated by Claude Opus's morning digest
 * (digest_action_items table) with status, assignee and progress per item.
 * Lets the manager see at-a-glance who's on what without leaving the
 * Overview.
 *
 * Tapping a row deep-links to the AI Insights page filtered by site
 * and date so the manager can update status, assign or upload evidence.
 */

const STATUS_META: Record<
  ActionItemSummary['status'],
  { label: string; pillClass: string; borderClass: string }
> = {
  open: {
    label: 'Open',
    pillClass: 'bg-status-critical/15 text-status-critical border-status-critical/40',
    borderClass: 'border-l-status-critical',
  },
  in_progress: {
    label: 'In progress',
    pillClass: 'bg-status-warning/12 text-status-warning border-status-warning/35',
    borderClass: 'border-l-status-warning',
  },
  done: {
    label: 'Done',
    pillClass: 'bg-status-success/12 text-status-success border-status-success/35',
    borderClass: 'border-l-status-success',
  },
  skipped: {
    label: 'Skipped',
    pillClass: 'bg-ink-muted/15 text-ink-secondary border-ink-muted/35',
    borderClass: 'border-l-ink-muted',
  },
};

export function ActionItems({ items }: { items: ActionItemSummary[] }) {
  const open = items.filter((i) => i.status === 'open' || i.status === 'in_progress').length;
  const done = items.filter((i) => i.status === 'done').length;

  return (
    <Card>
      <CardHeader>
        <div className="flex flex-wrap items-end justify-between gap-3">
          <div>
            <p className="label-badge text-brand-orange">Action items</p>
            <CardTitle className="mt-1 font-display text-xl">
              What your team is working on
            </CardTitle>
          </div>
          <div className="flex gap-4 text-xs text-ink-secondary">
            <span>
              <strong className="text-status-warning">{open}</strong> open / in&nbsp;progress
            </span>
            <span>
              <strong className="text-status-success">{done}</strong> done
            </span>
          </div>
        </div>
      </CardHeader>

      <CardContent>
        {items.length === 0 ? (
          <p className="py-8 text-center text-sm text-ink-muted">
            No action items yet — they appear once Claude&apos;s morning digest runs.
          </p>
        ) : (
          <ul className="space-y-2">
            {items.map((item) => {
              const status = STATUS_META[item.status];
              return (
                <li
                  key={item.id}
                  className={cn(
                    'group rounded-card border border-surface-border bg-surface-card',
                    'border-l-2 transition-colors hover:border-ink-muted/40',
                    status.borderClass,
                  )}
                >
                  <Link
                    href={`/ai-insights?site=${item.siteId}&date=${item.date}`}
                    className="flex items-start gap-4 p-4"
                  >
                    {/* Status pill */}
                    <div className="shrink-0 pt-0.5">
                      <span
                        className={cn(
                          'inline-flex items-center rounded-full border px-2.5 py-0.5 font-condensed text-[11px] font-bold uppercase tracking-label',
                          status.pillClass,
                        )}
                      >
                        {status.label}
                      </span>
                    </div>

                    {/* Action body */}
                    <div className="min-w-0 flex-1">
                      <p className="text-sm font-medium leading-snug text-ink-primary">
                        {item.actionText}
                      </p>
                      <div className="mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-ink-muted">
                        <span className="inline-flex items-center gap-1">
                          <MapPin className="h-3 w-3" /> {item.siteName}
                        </span>
                        <span className="inline-flex items-center gap-1">
                          <UserIcon className="h-3 w-3" />
                          {item.assignedTo ? (
                            item.assigneeEmail ?? 'Assigned'
                          ) : (
                            <em className="not-italic">Unassigned</em>
                          )}
                        </span>
                        <span className="inline-flex items-center gap-1">
                          <Clock className="h-3 w-3" /> {formatRelative(item.updatedAt)}
                        </span>
                      </div>

                      {item.notes && (
                        <p className="mt-2 rounded-btn border-l-2 border-brand-orange/40 bg-surface px-3 py-1.5 text-xs italic text-ink-secondary">
                          &ldquo;{item.notes}&rdquo;
                        </p>
                      )}
                    </div>

                    <ChevronRight className="mt-1 h-4 w-4 shrink-0 text-ink-muted transition-colors group-hover:text-brand-orange" />
                  </Link>
                </li>
              );
            })}
          </ul>
        )}

        {items.length > 0 && (
          <div className="mt-4 text-right">
            <Link
              href="/ai-insights"
              className="text-xs text-ink-secondary hover:text-brand-orange"
            >
              View all in AI Insights →
            </Link>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
